### ISSUE TITLE
Slow page load and profiler dump feature

### ISSUE THREAD

**Issue by colinmollenhour** [AOEpeople/Aoe_Profiler#1]
Feature request/idea (if I find time I may implement this):

Allow the profiler to be enabled for every request, but nothing should be rendered in the foreground. Instead, if the total page load time exceeds some threshold, the profiler data is dumped to a file in var/profiler using serialize(). Then an admin grid shows a list of these files and their modified times and you can click the row and view the fully rendered profiler data via the admin site. This is something like a slow query log in MySQL and would help identify slow pages or the cause of intermittent slow page loads in production.

To take it further it could be enabled only in certain cases, such as if the request matches a regex, or for some random sampling (e.g. 1% of page loads for really high-traffic sites).

**Comment by fbrnc** [comment]
Closing this since Aoe_Profiler now never displays any output on the frontend, but capture the data (currently in the database only) and then allows you to look at the data in the admin.
