### ISSUE TITLE
nginx 502 Bad Gatweay on frontend

### ISSUE THREAD

**Issue by perler** [AOEpeople/Aoe_Profiler#17]
Aoe Profiler works great on the backend, but when I add ?profile=1 to a frontend URL I quite often get a 502 Bad Gateway from nginx with this in the magento system.log: https://gist.github.com/perler/8557027

what could be the problem here?

**Comment by simonrl** [comment]
Having the same problem... does any1 have a solution?

My server:
Magento EE 1.12.
nginx 0.91-ubuntu1 with php-fpm

**Comment by fbrnc** [comment]
Hi,
I'm not sure if the entries in the log are related to the error you're seeing. 
Sadly in some places Magento's Varien_Profiler::start() and Varien_Profiler::stop() don't match correctly (e.g. if there's an early return in a method). Aoe_Profiler detects this and auto-corrects it. Unless you disabled logging Aoe_Profiler writes this into the log.

I assume the 502 Bad Gateway error is related to something else. Did you check PHP logs and Magento logs (system.log, exceptions,...)?

**Comment by simonrl** [comment]
Hey, sorry that I forgot to answer. In my case it was a simple memory issue, magento-log gave no result, but PHP log showed that there wasn't enough memory available. I had to raise it to 2G.
