### ISSUE TITLE
Undefined class constant 'Varien_Profiler::TYPE_DEFAULT'

### ISSUE THREAD

**Issue by Bogardo** [AOEpeople/Aoe_Profiler#20]
Getting the following error after installing:

Fatal error: Undefined class constant 'Varien_Profiler::TYPE_DEFAULT' in `app\code\core\Mage\Core\Model\Layout.php` on line 465

---
app\code\core\Mage\Core\Model\Layout.php
![](http://i.imgur.com/exHeOcM.png)

Platform: `Magento Enterprise 1.10.0.2`

**Comment by groggu** [comment]
Remember to copy the Varian and Zend folders that come with the module into the community folder on your server.

**Comment by fbrnc** [comment]
@Bogardo: Let me know if this is still a problem. Closing this issue for now.
