### ISSUE TITLE
Admin Profiling?

### ISSUE THREAD

**Issue by chrispotter** [AOEpeople/Aoe_Profiler#25]
Has functionality been removed to profile the Admin?

**Comment by fbrnc** [comment]
Hi Chris,
profiling the admin is still possible, but a couple of things changed:

1.) By default admin pages are blacklisted. Check the `requestUriBlackList` node in https://github.com/AOEpeople/Aoe_Profiler/blob/master/var/aoe_profiler.xml.sample
2.) Profile results aren't being shown on the same page anymore, instead they will be stored in the database and there's a new admin grid that allows you to look at the results (decoupled from the request that you've been profiling).

Hope this helps.

Cheers,
Fabrizio
