### ISSUE TITLE
cannot save customer in Backend

### ISSUE THREAD

**Issue by davidverholen** [AOEpeople/Aoe_Profiler#27]
Hey,

when the validateAction in the AdminHtml CustomerController is called, there is an Exception with the follwing Text:

Notice: Undefined offset: 2  in /var/www/brandung/fe/vendor/aoepeople/aoe_profiler/app/code/community/Varien/Profiler.php on line 85

https://github.com/AOEpeople/Aoe_Profiler/blob/384b6de6443b383fcc62ed4c4f76604e2c256c51/app/code/community/Varien/Profiler.php#L85

Profiler: v0.3.0
Magento: 1.9.1.0

I see you already made 41 commits since this release. Maybe it's time for a new stable? ;)

**Comment by fbrnc** [comment]
Hi David,

please checkout the latest version of the code: 
https://github.com/AOEpeople/Aoe_Profiler/blob/master/app/code/community/Varien/Profiler.php#L180

Cheers,
Fabrizio
