### ISSUE TITLE
Working in EE 1.14/CE 1.9?

### ISSUE THREAD

**Issue by christeefury** [AOEpeople/Aoe_Profiler#28]
Hi,

Are there any known conflicts with upgrading to EE 1.14 or CE 1.9 using this extension? I see the issue that @davidverholen posted regarding saving customers in the backend. Can anyone else confirm if it is working or not working for them?

Thank you,
Chris

**Comment by fbrnc** [comment]
Hi Chris,

I just tested it and it works fine. The issue that David reported was already fixed. 
Please use the latest version from GitHub.

Let me know if you experience any issues.

**Comment by christeefury** [comment]
Sweet! Thank you very much!
