### ISSUE TITLE
Profiler doesn't seem to profiling adminhtml

### ISSUE THREAD

**Issue by kanduvisla** [AOEpeople/Aoe_Profiler#30]
Unlike the documentation states, when I add `?profile=1` to the adminhtml URL, nothing gets profiled. The frontend does however get profiler when I use the same method.

When I set the trigger to `always` in the configuration it works in the adminhtml.

Magento CE 1.9.1.0

**Comment by chrispotter** [comment]
I just asked this an got the response found here: https://github.com/AOEpeople/Aoe_Profiler/issues/25

Hope this helps!
