### ISSUE TITLE
Add request information on the profile single view

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/Aoe_Profiler#33]
The profile single view is missing information about what request does it present. 
E.g. showing the url of the profiled request would be perfect

**Comment by mzeis** [comment]
@fbrnc: I added a info block to the detail view. For this and the following change requests I didn't do any refactoring of the structure, just followed along what was already there.

**Comment by fbrnc** [comment]
Thanks for contributing this! This has already been merged before.
