### ISSUE TITLE
Back button (from single view to the list view)

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/Aoe_Profiler#34]
It would be nice if the profiler single view page would have a "back to the list" button

**Comment by fbrnc** [comment]
Good point. Not a big deal. I hope I can get to this at some point in the near future (and there are some more Profiler related things I wanted to do). Feel free to submit a PR for this and the other issue :)

**Comment by mzeis** [comment]
@fbrnc I added the back button.
