### ISSUE TITLE
Profiler returns no detailed time entries

### ISSUE THREAD

**Issue by jhoelzl** [AOEpeople/Aoe_Profiler#37]
I installed Aoe_Profiler and activated it in Backend. However, no detailed time entries are shown (see attached image). Can you help me?

![aoe-profiler-data](https://cloud.githubusercontent.com/assets/638936/9733806/90a24cb0-562e-11e5-8fa7-e2b17f1cb905.png)

**Comment by fbrnc** [comment]
Hi @jhoelzl,
is this the latest version from GitHub? Looks like something is interfering with the Profiler's output which used to happen when the output was rendered in the frontend. A while ago I changed this to capture all information in the DB and then you can pick a profile run in the backend and look at it there...

**Comment by jhoelzl** [comment]
Hi @fbrnc, yes it is the latest version.When i go to the backend, the profiler output works correctly. I have installed CE 1.7.0.2 with patches.

**Comment by jhoelzl** [comment]
Some boostrap CSS was interfering with the class "progress-bar" and changed the styling in frontend. I could resolve this.
