### ISSUE TITLE
compatibility with patch SUPEE-6788

### ISSUE THREAD

**Issue by danielepennati** [AOEpeople/Aoe_Profiler#43]
Hello,
we are using Aoe_Prifiler (v 0.2.2) on some magento website. I'd like to know if it is compatible with the new SUPEE-6788 Magento Patch that introduce some Backward Compatibility Issue: https://info2.magento.com/rs/318-XBX-392/images/SUPEE-6788-Technical%20Details.pdf

Thanks
daniele

**Comment by arosenhagen** [comment]
as for the admin routing, this extension is already compatible
